parameters:
  # Required
  - name: "ENVIRONMENT"
    type: string
    values:
      - DEV
      - UAT
  - name: "CHECKOUT_RESOURCE_REPO_NAME"
    type: string
    default: self

steps:
  - checkout: ${{parameters.CHECKOUT_RESOURCE_REPO_NAME}}
  - script: |
      rm -f e2e-tests/.env && cp e2e-tests/dev.env e2e-tests/.env
    displayName: 'Set env for E2E test (DEV)'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'DEV'))
  - script: |
      rm -f e2e-tests/.env && cp e2e-tests/uat.env e2e-tests/.env
    displayName: 'Set env for E2E test (UAT)'
    condition: and(succeeded(), eq('${{parameters.ENVIRONMENT}}', 'UAT'))
  - script: |
      cd e2e-tests && yarn install
    displayName: 'Yarn install'
  - script: |
      cd e2e-tests && yarn test src/auth/checkout.login-availability.integration.test.ts
    displayName: 'Checkout login test'
    continueOnError: true  
  - script: |
      cd e2e-tests && yarn test src/auth/checkout.npg-payment-auth.integration.test.ts
    displayName: 'Checkout authenticated transactions test'
    continueOnError: true    
  - script: |
      cd e2e-tests && yarn test src/auth/checkout.spid-auth.integration.test.ts
    displayName: 'Checkout spid test'
    continueOnError: true   
  - script: |
      cd e2e-tests && yarn test src/npg/checkout.npg.integration.test.ts
    displayName: 'Checkout NPG integration test'
    continueOnError: true     
  - script: |
      cd e2e-tests && yarn test src/npg/psp-sorting.npg.integration.test.ts
    displayName: 'Checkout PSP sorting test'
    continueOnError: true       
  - script: |
      cd e2e-tests && yarn test src/npg/psp-unavailable-error.npg.integration.test.ts
    displayName: 'Checkout PSP unavailable test'
    continueOnError: true        
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml' 
      searchFolder: '$(System.DefaultWorkingDirectory)'
    condition: succeededOrFailed()
